# for dev environment
version: "3.8"

services:
  backend:
    image: hsunami10/fastapi-postgresql-starter
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_DEV_DEPS=${INSTALL_DEV_DEPS-true}
    ports:
      - 8080:8000
    depends_on:
      - database
    volumes:
      - ./:/opt/app/
  database:
    image: postgres:16
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env.template # changethis to .env
    ports:
      - 5555:5432
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata

volumes:
  app-db-data:

networks:
  default:
    name: app_network