# for dev environment
# TODO: Refactor to compose.override.yml (dev) and compose.yml for prod
version: "3.8"

services:
  backend-api:
    image: ${DOCKER_IMAGE_BACKEND_API?Variable not set in env}:${TAG-latest}
    env_file:
      - .env
    environment:
      - ENVIRONMENT=DEVELOPMENT
      - DEV_ENV=DOCKER
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Override this when running "docker compose"
        - INSTALL_DEV_DEPS=${INSTALL_DEV_DEPS-true}
    restart: always
    ports:
      - 8080:8000
      - 5678:5555
    depends_on:
      - pg-db
    volumes:
      - ./:/opt/app/
    networks:
      - frontnet
      - backnet
  # Same as POSTGRES_HOST
  pg-db:
    image: postgres:16
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    networks:
      - backnet

volumes:
  db-data:

networks:
  frontnet:
  backnet: