# for dev environment
version: "3.8"
services:
  backend:
    image: hsunami10/fastapi-postgresql-starter
    container_name: fastapi-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_ENV=${APP_ENV-development}
    ports:
      - 8080:8000
    depends_on:
      - postgres
    volumes:
      - ./:/opt/app/
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env.template # changethis
    ports:
      - 5432:5432
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
volumes:
  app-db-data: