# Replace <proj-root-path> with pwd
# This only works if docker compose is running
windows:
  - name: Project Root
    root: <proj-root-path>
    panes:
      - ''
  - name: Frontend Dev
    root: <proj-root-path>/frontend
    # layout: even-horizontal
    panes:
      - npm run dev
  - name: Backend Dev
    root: <proj-root-path>/backend
    layout: main-vertical
    panes:
      - commands:
        - echo "Entering Poetry virtual environment..." && source "$(poetry env info -p)/bin/activate"
        name: poetry venv (Python)
        focus: true
      - commands:
        - docker compose attach backend-api
        name: FastAPI stdout (backend-api service)
      - commands:
        - docker compose attach pg-db
        name: PostgreSQL stdout (pg-db service)
