# Assuming project root = frontend/, backend/, compose.yml
# This only works if docker compose is running
# TODO: test
windows:
  - name: GitHub Root
    root: <proj-root-path>
    panes:
      - ''
  # - name: Frontend Dev
  #   root: <proj-root-path>
  #   layout: even-horizontal
  #   panes:
  #     - docker compose attach frontend-client
  #     - docker compose exec frontend-client npx tsc --watch
  - name: Backend Dev
    root: <proj-root-path>
    layout: even-horizontal
    panes:
      - docker compose attach backend-api
      - docker compose attach pg-db
